---
- name: "install plugin from binaries.sonarsource.com"
  include: prepare_binary_plugin.yml
  when: not sonar_cplugin.get('marketplace', false)|bool

- name: "install plugin from updates.sonarsource.com"
  include: prepare_marketplace_plugin.yml
  when: sonar_cplugin.get('marketplace', false)|bool

- name: "{{ sonar_cplugin.name }} | Download current plugin"
  get_url:
    url: "{{ cplugin_url }}"
    dest: "{{ __sonar_plugin_home }}"
    owner: "{{ sonar_user }}"
    group: "{{ sonar_group }}"
    mode: "0644"
  retries: 5
  delay: 10
  notify:
    - "restart SonarQube service"
