galaxy_info:
  author: Guillaume Charbonnier
  description: Update system packages and install default packages

  license: MIT
  min_ansible_version: 2.2

  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
    - name: Debian
      versions:
        - jessie
        - stretch

  galaxy_tags:
    - apt-get
    - apt

dependencies: []
