galaxy_info:
  author: Guillaume Charbonnier
  description: Install Nebula overlay network

  license: MIT
  min_ansible_version: 2.2

  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - focal
        - jammy

  galaxy_tags:
    - nebula
    - systemd

dependencies: []
