galaxy_info:
  author: Guillaume Charbonnier
  description: Set timezone and configure systemd-timesyncd

  license: MIT
  min_ansible_version: 2.2

  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
    - name: Debian
      versions:
        - jessie
        - stretch
    - name: ArchLinux
      versions:
        - all
        - any
    - name: EL
      versions:
        - 7
    - name: Fedora
      versions:
        - 30

  galaxy_tags:
    - systemd
    - ntp
    - systemd-timesyncd
    - timesync
    - time
    - timedatectl

dependencies: []
